### ISSUE TITLE
Tag CakePHP 4.x compatible release

### ISSUE THREAD

**Issue by challgren** [bcrowe/cakephp-encrypted-type#4]
Can you please tag version 2.0.0 from the cake-4.x branch.

**Comment by challgren** [comment]
Ping @bcrowe also if you aren't interesting in handling this plugin anymore I would be happy to take over it for you.

**Comment by bmudda** [comment]
@bcrowe are you planning to do a release for this anytime soon?

**Comment by challgren** [comment]
Bump @bcrowe.

**Comment by bcrowe** [comment]
@challgren @bmudda Hey guys. Extremely sorry for the big delay. I've gotten this merged, and tagged with a 2.0.0 release. I've moved the CakePHP 3.x code into a 1.x branch. CakePHP 4.x code will live in master and be 2.x.x tags. Thanks for the help!

**Comment by challgren** [comment]
@bcrowe no worries if you ever need help with this let me know. Seems pretty stable so shouldn't really need much maintenance besides releases for newer cake versions.

**Comment by challgren** [comment]
@bcrowe not sure if you saw but https://scrutinizer-ci.com/g/bcrowe/cakephp-encrypted-type/code-structure shows the Github token has expired so it hasn't been updated with the latest coverage.
