### ISSUE TITLE
Update composer dependency for CakePHP

### ISSUE THREAD

**Issue by bmudda** [bcrowe/cakephp-encrypted-type#5]
Currently the CakePHP version required in composer.json is `4.x-dev as 4.0.0`. I get the following error trying to install version `2.0.0` with a CakePHP version of ``
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bcrowe/cakephp-encrypted-type ~2 -> satisfiable by bcrowe/cakephp-encrypted-type[2.0.0].
    - bcrowe/cakephp-encrypted-type 2.0.0 requires cakephp/cakephp 4.x-dev as 4.0.0 -> no matching package found.
```
Can you please change the composer.json CakePHP requirement to `"cakephp/cakephp": "^4.0"` so we will be able to use this when we upgrade to CakePHP 4.1 as well?

**Comment by hacheraw** [comment]
Please @bcrowe

**Comment by doonot** [comment]
This is also preventing us from upgrading to CakePHP 4.x. Please update it.

**Comment by bmudda** [comment]
@bcrowe can you please create a new tag? The latest tag `2.0.0` still has `"cakephp/cakephp": "4.x-dev as 4.0.0"` in composer.json and we still can't use it with CakePHP 4.1 or 4.2

**Comment by bcrowe** [comment]
@bmudda Tagged as 2.0.1!

**Comment by bmudda** [comment]
@bcrowe Thanks for the new tag. But tag is not yet available on https://packagist.org/packages/bcrowe/cakephp-encrypted-type 

There is a note there that states that the package is not auto updated. Since it's not in packagist, composer can't find that version.
```
This package is not auto-updated.
Last update: 2021-01-09 09:51:42 UTC
```

**Comment by bcrowe** [comment]
Interesting. Trying to log into Packagist now to kick it, but keep getting "Account could not be linked correctly." error. Let me see what I can do here.

**Comment by bmudda** [comment]
@bcrowe the 2.0.1 version is there now and I can pull it with composer. Thank you!
