### ISSUE TITLE
array data ?

### ISSUE THREAD

**Issue by Erwane** [bcrowe/cakephp-encrypted-type#7]
Hi,
May this plugin could support array data with json_encode in `toDatabase` and json_decode in `toPhp` methods ?
I can make pr if it's good for you.

**Comment by bcrowe** [comment]
Of course. PR is welcomed! Sorry for the delay. I'll keep my eyes out.

**Comment by bcrowe** [comment]
Gonna close this for now. @Erwane Feel free to add support for this though in a PR.
